<div id="navegacion" prev="../Ejercicios_Tema_6/uso_numpy.html" next=""></div>

<div class="section-title">Sección 3.7</div>

# Ejercicios 

Los enlaces que te encuentres en esta página, solo funcionan desde el formato html, no desde el notebook una vez descargado.

## Ejercicio 1

El fichero [rotterdam_rainfall.txt](./datos/rotterdam_rainfall.txt) recoge los datos de las precipitaciones diarias de la estación meteorológica de Rotterdam en 2012.

* La primera columna representa la fecha.
* La segunda columna representa la cantidad de precipitaciones expresado en 0.1 mm (-1 si es menor a 0.05 mm).
* El separador de campos es el caracter `, `.

__a)__ Crear un array de `numpy` con los datos del fichero [rotterdam_rainfall.txt](./datos/rotterdam_rainfall.txt). El array ha de llamarse `precipitaciones`.

   * Descarga el fichero  en tu directorio de trabajo.
   * Carga el fichero mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`.

In [57]:
# Sol
import numpy as np
precipitaciones=np.loadtxt("rotterdam_rainfall.txt", delimiter=",", dtype="int")

__b)__ Averigua el número de días donde la cantidad de precipitaciones es mayor a 0.05 mm (valor mayor que -1).
    
* Primero crea un filtro donde la cantidad de precipitaciones (columna 1) sea mayor que  -1.
* Aplica el filtro al array `precipitaciones`. Guarda el resultado en un nuevo array llamado `precip_positivas`.
* Puedes usar la función `len` para calcular el tamaño del array  `precip_positivas`.

In [17]:
# Sol: 324 días 
filtro=precipitaciones[:,1]>-1
precip_positivas=precipitaciones[filtro]
len(precip_positivas)

324


__c)__ Calcula el valor medio de la cantidad de precipitación. No tengas en cuenta las precipitaciones con valor -1, por tanto usa el array `precip_positivas` para calcular dicho valor medio.

   * Utiliza la función `mean`.
    


In [23]:
# Sol: 30.700617283950617

np.mean(precip_positivas[:,1])

30.700617283950617

__d)__ Calcula el día que ha tenido mayor cantidad de precipitación y la cantidad de precipitación.

   * Utiliza las funciones `argmax` y `max`.

In [44]:
# Sol: Máxima precipitación: 224. 
#      Día de máxima precipitación : 20121222
print("Máxima precipitación:", np.max(precipitaciones[:,1]))
print("Día de máxima precipitación :", precipitaciones[np.argmax(precipitaciones[:,1]),0])


Máxima precipitación: 224
Día de máxima precipitación : 20121222


__e)__ Expresa la cantidad de precipitación en mm. Para ello multiplica la cantidad de precipitación por 10.

   

In [61]:
# Sol: Los primeros valores del resultado son:

#    array([[20120101,     2070],
#           [20120102,      -10],
#           [20120103,     1440],
#           [20120104,      360],
#            ...
#            ...

precipitaciones_mm=precipitaciones.copy()
precipitaciones_mm[:,1]*=10
precipitaciones_mm


array([[20120101,     2070],
       [20120102,      -10],
       [20120103,     1440],
       [20120104,      360],
       [20120105,      840],
       [20120106,       80],
       [20120107,      300],
       [20120108,      -10],
       [20120109,       80],
       [20120110,        0],
       [20120111,      100],
       [20120112,       90],
       [20120113,       40],
       [20120114,      -10],
       [20120115,        0],
       [20120116,        0],
       [20120117,        0],
       [20120118,      320],
       [20120119,     1440],
       [20120120,      -10],
       [20120121,      350],
       [20120122,      190],
       [20120123,      160],
       [20120124,       50],
       [20120125,       50],
       [20120126,      330],
       [20120127,      -10],
       [20120128,      -10],
       [20120129,        0],
       [20120130,       10],
       [20120131,      -10],
       [20120201,        0],
       [20120202,        0],
       [20120203,      270],
       [201202

## Ejercicio 2

Dos niños están haciendo una colección de cromos. Cada cromo tiene asignado un número entero entre 1 y 200.

* Los cromos que tiene Juan se encuentran en el fichero [juan.txt](./datos/col_juan.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Juan.

* Los cromos que tiene Pedro se encuentran en el fichero [pedro.txt](./datos/col_pedro.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Pedro.

__a)__ Crear un array de `numpy` con los datos de cada una de las colecciones. Los arrays han de llamarse `juan`y `pedro`.

   * Descarga los ficheros  en tu directorio de trabajo.
   * Carga cada uno de los ficheros mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`.

In [8]:
# Sol: 
import numpy as np

juan=np.loadtxt("col_juan.txt", delimiter= ",", dtype= "float")
pedro=np.loadtxt("col_pedro.txt", delimiter= ",", dtype= "float")


__b)__ Calcula el número de cromos diferentes que tiene cada niño. 

In [14]:
# SOl: 
# juan tiene 68 cromos
# pedro tiene 124 cromos

print("juan", len((juan)))
print("pedro", len((pedro)))

juan 68
pedro 124


__c)__ Calcula el número de cromos totales que tiene cada niño (contando los cromos repetidos). 

In [17]:
# SOl: 
# pedro tiene 1326 cromos 
# juan tiene 619 cromos

print("pedro", np.sum(pedro[:,1]))
print("juan", np.sum(juan[:,1]))

pedro 1326.0
juan 619.0


__d)__ Calcula el número de cromos que aparecen en las dos colecciones. Puedes usar la función `np.intersect1d`.

In [21]:
# Sol
# Hay 44 cromos que aparecen en las dos colecciones
print(len(np.intersect1d(pedro[:,0], juan[:,0])))

44


__e)__ Entre los dos niños, ¿forman la colección completa?. Puedes usar la función `np.union1d`.

In [22]:
# Sol: 
# No Forman la colección completa. Entre los dos, solo tienen 148 cromos distintos y la colección tiene 200 cromos

print(len(np.union1d(pedro[:,0], juan[:,0])))

148


__f)__ ¿Qué números faltan para tener la colección completa?

* Puedes generar un array de todos los cromos de la colección con la función `arange`.
* Usa la función `np.in1d` 

In [35]:
# Sol:
# Listado de los cromos que faltan:
#      [  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
#        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
#       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
#       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200]
    
np.arange(1,201)[~np.in1d(np.arange(1,201),np.union1d(pedro[:,0], juan[:,0]))]

array([  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200])

---------------------